version: '3'
services:
  app:
    user: ${UID}:${GID}
    build: .
    command: yarn dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ~/.ssh:/home/node/.ssh
      - node_modules-store:/app/node_modules
volumes:
  node_modules-store:
